In [53]:
import numpy as np

def create_board():
    zero_array = np.zeros([3,3], int)
    return zero_array

board = create_board()
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf

position = ([1,2], int)
def place(board, player, position):    
    board[position] = player
        
place(board, 1, (0,0))
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf

def possibilities(board):
    return list(zip(*np.where(board <= 0)))
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf

import random 
random.seed(1)

# write your code here!
def random_place(board, player):    
    pos = random.choice(possibilities(board))
    board[pos] = player
    return board

random_place(board, 2)
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf

def row_win(board, player):
    return [player, player, player] in board.tolist()
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf


def col_win(board, player):
    board_transpose = np.transpose(board)
    return [player, player, player] in board_transpose.tolist()
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf


def diag_win(board, player):
    Win_diag = 0
    diag1 = np.zeros([1,3], int)
    diag2 = np.zeros([1,3], int)
    X = [0,1,2]

    for i in X:
        diag1[0,i] = board[i,i]
        
    for i in X:
        diag2[0,i] = board[i, 2-i]
    
    Check_diag1 = ([player, player, player] in diag1.tolist())
    Check_diag2 = ([player, player, player] in diag2.tolist())
    
    if (Check_diag1 == True) or (Check_diag2 == True):
        Win_diag = 1
    return Win_diag
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf


def evaluate(board):
    P = np.array([0,0])
    for player in [1,2]:
        # add your code here!
        row_win(board, player)
        col_win(board, player)
        diag_win(board, player)
        if(row_win(board, player) == True or col_win(board, player) == True or diag_win(board, player) == True) and P[player-1] == 0:
            P[player-1] = 1
    
    for i in [0,1]:
        if P[i] != 0:
            print("the winner: ", i+1)
    
    print('\n')
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf
    
       
def play_game():
    board = create_board()
    
    x = [1,2,1,2,1,2,1,2]

    for i in x:
        random_place(board, x[i-1])

    print(board)
    evaluate(board)
#gdhsj,sfkjsd.fks.ksf/dsddbfgnghnmhj,n.m,,.jhkghjghfghfghfghfghf

    
for j in range(15):
    play_game()


[[1 1 0]
 [2 1 2]
 [2 1 2]]
the winner:  1


[[2 2 2]
 [1 0 1]
 [1 1 2]]
the winner:  2


[[2 2 2]
 [1 2 0]
 [1 1 1]]
the winner:  1
the winner:  2


[[1 2 1]
 [2 0 1]
 [2 1 2]]


[[2 2 2]
 [0 1 1]
 [1 1 2]]
the winner:  2


[[1 2 0]
 [2 2 1]
 [1 1 2]]


[[2 2 1]
 [0 1 2]
 [1 2 1]]
the winner:  1


[[0 1 1]
 [2 1 2]
 [2 2 1]]


[[2 0 2]
 [2 1 1]
 [2 1 1]]
the winner:  2


[[2 2 2]
 [1 1 1]
 [1 2 0]]
the winner:  1
the winner:  2


[[1 1 1]
 [1 0 2]
 [2 2 2]]
the winner:  1
the winner:  2


[[2 1 2]
 [1 1 2]
 [1 2 0]]


[[2 1 1]
 [0 2 2]
 [1 2 1]]


[[1 1 2]
 [0 2 1]
 [1 2 2]]


[[0 1 2]
 [2 2 1]
 [1 1 2]]


